apiVersion: v1
data:
  mapAccounts: |2
      - 992927038462
  mapRoles: |2
      - rolearn: arn:aws:iam::992927038462:role/my-eks-cluster_role
        username: fargate_pod_execution_role
        groups:
          - system:masters

      - rolearn: arn:aws:iam::992927038462:role/fargate_pod_execution_role
        username: my-eks-cluster-role
        groups:
          - system:masters

  mapUsers: |2
      - userarn: arn:aws:iam::992927038462:user/bzamora
        username: bzamora
        groups:
          - system:masters

      - userarn: arn:aws:iam::992927038462:user/bcaceres
        username: bcaceres
        groups:
          - system:masters

      - userarn: arn:aws:iam::992927038462:user/pipelines
        username: pipelines
        groups:
          - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
