apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: kube-system
data:
  awslogs.conf: |
    [general]
    state_file = /var/awslogs/state/agent-state

    [/var/log/dmesg]
    file = /var/log/dmesg
    log_stream_name = {instance_id}/dmesg
    log_group_name = /aws/eks/{cluster_name}/var/log/dmesg
    datetime_format = %b %d %H:%M:%S

    [/var/log/messages]
    file = /var/log/messages
    log_stream_name = {instance_id}/messages
    log_group_name = /aws/eks/{cluster_name}/var/log/messages
    datetime_format = %b %d %H:%M:%S

    [/var/log/docker]
    file = /var/log/docker
    log_stream_name = {instance_id}/docker
    log_group_name = /aws/eks/{cluster_name}/var/log/docker
    datetime_format = %Y-%m-%dT%H:%M:%S.%f

    [/var/log/eks/audit.log]
    file = /var/log/eks/audit.log
    log_stream_name = {instance_id}/audit
    log_group_name = /aws/eks/{cluster_name}/var/log/audit.log
    datetime_format = %Y-%m-%dT%H:%M:%SZ

    [/var/log/eks/authenticator.log]
    file = /var/log/eks/authenticator.log
    log_stream_name = {instance_id}/authenticator
    log_group_name = /aws/eks/{cluster_name}/var/log/authenticator.log
    datetime_format = %Y-%m-%dT%H:%M:%SZ
